### ISSUE TITLE
toolbarExternal with multiple editors

### ISSUE THREAD

**Issue by manufaktor** [html5cat/redactor-js#39]
When having multiple instances of the redactor editor on a page and using a single toolbar through the `toolbarExternal` option, there are a few cases where the wrong editor gets focus when using the toolbar.

**I have discovered these cases so far, where always the last editor instance is affected and not the one where I was currently editing:**
- Inserting an image inserts into the last editor on the page
- Toggling HTML view always toggles the last editor on the page

**Comment by MichaelHindley** [comment]
Inserting table also fails with this error. As does any custom button that inserts into "active" editor.

**Comment by kroofy** [comment]
Issue seems to be related to all buttons with menu drop-downs or modal windows connected to them. Simply due to the fact that clicking them blurs the focus from the editor and the blur event is never captured by Redactor, therefore never being able to restore focus to the previously blurred editor.

I looked at the code but didn't manage to fix it.

**Comment by kroofy** [comment]
I created a plugin that seems to be working fine, but I've just been testing it for a short while.

The issue seems to be that `externalToolbar` wasn't designed with multiple editors in mind, at least not by using just a single toolbar. So what you need to do is to create one unique toolbar for each editor and then show and hide them based on what editor is in focus.

I created a plugin that handles that. Take a look here https://github.com/kroofy/externalswitcher and tell me what you think.

**Comment by MichaelHindley** [comment]
Well, it works, however, it's just not feasible when you have more than a few editable elements on a page due to performance reasons. Especially if it's a mobile-focused tool.

The plugin puts some makeup on the problem but doesn't solve it, the problem as defined is to have one toolbar for multiple editors.

**Comment by kroofy** [comment]
Right, I will however use this or a similar solution in a production environment. Although I will have no more than 3 editors per page and it's not designed for mobile, so I guess I will not have any performance issues. Have you experienced any severe performance issues while using a similar solution? Would be nice to know since I probably have to opt for a solution like this.

Update: Just took a look at the timeline, no action exceeds 15 ms. Most of them are just a couple of ms high. While others are insignificant.
