### ISSUE TITLE
Redactor 9

### ISSUE THREAD

**Issue by t3chn0r** [html5cat/redactor-js#66]
I just saw a tweet from Imperavi about releasing Redactor 9, will this repository be updated to this new release?

How active is this repo as before Redactor 9, Redactor was at a version 8.2.5 but the repo seems stuck at 8.2.2 and what happens with changes suggested by people here? Are those changes accepted or not?

I'm not sure exactly how this repo "works" with the official version.

**Comment by html5cat** [comment]
@t3chn0r originally the project had MIT/GPL license. Then it was switched to CC and now it looks like only commercial licenses are available. So I'm afraid this project doesn't have a very bright future on GitHub.

I'm not the author and I created this project so that the code is easily accessible and there's an option for the team to collect feedback. I've been in touch with Imperavi regarding transferring the account but they were not interested.

**Comment by t3chn0r** [comment]
Thanks @dybskiy, thanks for your answer. I had a feeling something like that was happening.
