### ISSUE TITLE
Image & Files Upload JSON Data

### ISSUE THREAD

**Issue by jamesmehorter** [html5cat/redactor-js#74]
How can I specify additional data arguments to the AJAX image and file upload? I.e. typically with  jQuery.ajax() you can send something like: 

```
$.ajax({ 
    url: my_serverside_ajax.php, 
    type:'POST',
    data: {action: 'some_ajax_action', foo: 'bar'}
    success: function(response) {
        //ajax complete
    }
});
```

A good example is WordPress AJAX, where all ajax requests are sent to the same admin-ajax.php file and each has it's own 'action' sent over POST. That way in the server-side PHP file you can have code like: 

```
<?php
    if ($_POST['action'] == 'my-image-upload') : 
        //do something with $_FILES
    endif;
```

Thanks!

**Comment by jamesmehorter** [comment]
Was this answered / corrected?

**Comment by html5cat** [comment]
Hey. Not in this repo unfortunately.

This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase.

Please download the latest version from http://imperavi.com/redactor/

Happy to transfer ownership if you want to maintain a fork.
