### ISSUE TITLE
THIS PROJECT IS NO LONGER MAINTAINED

### ISSUE THREAD

**Issue by leeoniya** [html5cat/redactor-js#94]
Redactor is now a commercial-only product and this codebase is no longer maintained; issues are not reviewed and will not be fixed.

The README should be updated to reflect this so that people do not come here to file new issues and expecting feedback.

**Comment by html5cat** [comment]
Since the moment authors changed license this repo's value became very questionable.
On one hand I should have closed it long ago, on the other hand it still has some utility.
I've added https://github.com/dybskiy/redactor-js/blob/master/CONTRIBUTING.md a while back, will update readme to make it more clear.

**Comment by leeoniya** [comment]
thanks!
